(() => {
  'use strict';
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const C={flea:{l:'Floh-/Trödelmarkt',i:'🧺',c:'#f6c85f'},harvest:{l:'Ernte & Hof',i:'🎃',c:'#e99043'},town:{l:'Stadt-/Dorffest',i:'🎉',c:'#7f8cff'},craft:{l:'Markt & Handwerk',i:'🛍️',c:'#d97adf'},christmas:{l:'Weihnachtsmarkt',i:'🎄',c:'#55c28d'},weekly:{l:'Wochenmarkt',i:'🥕',c:'#6bc5a4'},other:{l:'Weitere Feste',i:'🎪',c:'#73b8ef'}};
  const berlin=new Set(['mitte','friedrichshain kreuzberg','pankow','charlottenburg wilmersdorf','spandau','steglitz zehlendorf','tempelhof schoneberg','neukolln','treptow kopenick','marzahn hellersdorf','lichtenberg','reinickendorf']);
  const S={events:[],filtered:[],region:'all',preset:'today',cats:new Set(Object.keys(C)),loc:null,map:null,layer:null,markers:new Map()};
  function parseDate(v){if(!v)return null;if(/^\d{4}-\d{2}-\d{2}/.test(v))return new Date(v.slice(0,10)+'T00:00:00');const m=String(v).match(/(\d{1,2})\.(\d{1,2})\.(\d{4})/);return m?new Date(+m[3],+m[2]-1,+m[1]):null}
  function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function start(d){const x=new Date(d);x.setHours(0,0,0,0);return x} function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function cat(e){const t=norm([e.title,e.notes,e.sourceType,e.organizer].join(' '));if(/weihnacht|advent/.test(t))return'christmas';if(/floh|trodel|antikmarkt|sammel/.test(t))return'flea';if(/ernte|kurbis|bauern|hoffest|apfel|kartoffel/.test(t))return'harvest';if(/dorf fest|dorffest|stadtfest|volksfest|strassenfest|angerfest|heimatfest|flosserfest|hussitenfest/.test(t))return'town';if(/kunsthand|handwerk|kunstmarkt|basar/.test(t))return'craft';if(e.sourceType==='weekly')return'weekly';return'other'}
  function region(e){const d=norm(e.district),p=norm(e.place);return berlin.has(d)||d==='berlin'||p==='berlin'?'berlin':'brandenburg'}
  function key(e){return'eventpref:'+norm([e.title,e.address,e.zip,e.place].join('|')).slice(0,220)}
  function pref(e){try{return JSON.parse(localStorage.getItem(key(e))||'{}')}catch{return{}}} function save(e,p){localStorage.setItem(key(e),JSON.stringify({...p,title:e.title,address:e.address,zip:e.zip,place:e.place,updatedAt:new Date().toISOString()}))}
  function allPrefs(){const a=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith('eventpref:'))continue;try{const p=JSON.parse(localStorage.getItem(k));if(p.visited||p.rating||p.note||p.favorite||p.avoid)a.push(p)}catch{}}return a.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')))}
  function hav(a,b){const R=6371,r=x=>x*Math.PI/180,d1=r(b[0]-a[0]),d2=r(b[1]-a[1]),q=Math.sin(d1/2)**2+Math.cos(r(a[0]))*Math.cos(r(b[0]))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
  function dist(e){return S.loc&&Number.isFinite(e.lat)&&Number.isFinite(e.lon)?hav(S.loc,[e.lat,e.lon]):null}
  function dateRange(){if($('date').value){const d=new Date($('date').value+'T00:00:00');return[d,d]}const n=start(new Date());if(S.preset==='today')return[n,n];if(S.preset==='tomorrow')return[add(n,1),add(n,1)];if(S.preset==='weekend'||S.preset==='nextWeekend'){let x=(6-n.getDay()+7)%7;if(S.preset==='nextWeekend')x+=x===0?7:7;const sa=add(n,x),su=add(sa,1);return[sa,su]}return null}
  function occurs(e,a,b){const f=parseDate(e.from),t=parseDate(e.to)||f;if(!a)return !t||t>=start(new Date());if(!f)return true;return start(t||f)>=start(a)&&start(f)<=start(b)}
  function passesTime(e){if(!$('time').value&&!$('openNow').checked)return true;const txt=String(e.timeText||'');const ms=[...txt.matchAll(/(\d{1,2})(?::(\d{2}))?\s*(?:-|bis)\s*(\d{1,2})(?::(\d{2}))?/gi)];if(!ms.length)return true;const m=ms[0],from=+m[1]*60+(+m[2]||0),to=+m[3]*60+(+m[4]||0);if($('openNow').checked){const n=new Date(),v=n.getHours()*60+n.getMinutes();return v>=from&&v<=to}const [h,mi]=$('time').value.split(':').map(Number);return to>=h*60+mi}
  function doFilter(){const q=norm($('search').value),r=dateRange(),rad=+$('radius').value;S.filtered=S.events.filter(e=>{const p=pref(e),d=dist(e);if(!S.cats.has(e.category))return false;if(S.region!=='all'&&e.region!==S.region)return false;if(q&&!norm([e.title,e.place,e.address,e.district,e.notes].join(' ')).includes(q))return false;if(r&&!occurs(e,r[0],r[1]))return false;if(!passesTime(e))return false;if(S.loc&&rad<999&&d!=null&&d>rad)return false;if($('hideBad').checked&&(p.avoid||(+p.rating>0&&+p.rating<=4)))return false;if($('favorites').checked&&!p.favorite)return false;if($('visited').checked&&!p.visited)return false;return true});const sort=$('sort').value;S.filtered.sort((a,b)=>sort==='distance'?(dist(a)??1e9)-(dist(b)??1e9):sort==='rating'?(+pref(b).rating||0)-(+pref(a).rating||0):(parseDate(a.from)?.getTime()||9e15)-(parseDate(b.from)?.getTime()||9e15));render()}
  function fmt(e){const f=parseDate(e.from),t=parseDate(e.to);if(!f)return'laufend';const opt={weekday:'short',day:'2-digit',month:'2-digit'};return t&&iso(t)!==iso(f)?`${f.toLocaleDateString('de-DE',opt)} – ${t.toLocaleDateString('de-DE',opt)}`:f.toLocaleDateString('de-DE',opt)}
  function card(e){const p=pref(e),d=dist(e),c=C[e.category];const el=document.createElement('article');el.className='event-card';el.innerHTML=`<div class="event-icon">${c.i}</div><div><div class="event-title">${esc(e.title)}</div><div class="event-meta">${esc(fmt(e))}${e.timeText?' · '+esc(e.timeText):''}<br>${esc([e.address,e.zip,e.place].filter(Boolean).join(', '))}</div><div class="badges">${p.visited?'<span class="badge good">✓ besucht</span>':''}${p.rating?`<span class="badge ${+p.rating<=4?'bad':'good'}">${esc(p.rating)}/10</span>`:''}${p.favorite?'<span class="badge good">★ Favorit</span>':''}${p.avoid?'<span class="badge bad">nicht nochmal</span>':''}${e.sourceType==='havelblick'?'<span class="badge">Havelblick</span>':''}</div></div><div class="distance">${d==null?'':d.toFixed(1)+' km'}</div>`;el.addEventListener('click',()=>detail(e));return el}
  function render(){const host=$('events');host.innerHTML='';S.filtered.forEach(e=>host.append(card(e)));if(!S.filtered.length)host.innerHTML='<div class="empty">Keine passenden Termine. Ändere Datum, Kategorie oder Region.</div>';$('count').textContent=S.filtered.length;$('todayCount').textContent=S.events.filter(e=>occurs(e,start(new Date()),start(new Date()))).length;$('visitedCount').textContent=allPrefs().filter(x=>x.visited).length;$('subline').textContent=S.filtered.length?'Karte und Liste sind synchronisiert.':'';renderMap()}
  function renderMap(){S.layer.clearLayers();S.markers.clear();for(const e of S.filtered){if(!Number.isFinite(e.lat)||!Number.isFinite(e.lon))continue;const c=C[e.category];const icon=L.divIcon({className:'',html:`<div class="pin" style="--cat:${c.c}"><span>${c.i}</span></div>`,iconSize:[28,28],iconAnchor:[14,28]});const m=L.marker([e.lat,e.lon],{icon}).addTo(S.layer).bindTooltip(`${e.title} · ${fmt(e)}`);m.on('click',()=>detail(e));S.markers.set(e.id,m)}}
  function open(id,bg){$(id).classList.add('open');$(bg).classList.remove('hidden')} function close(id,bg){$(id).classList.remove('open');$(bg).classList.add('hidden')}
  function detail(e){const p=pref(e),c=C[e.category],nav=`https://www.openstreetmap.org/directions?to=${encodeURIComponent(e.lat+','+e.lon)}`;$('detail').innerHTML=`<div class="detail-kicker">${c.i} ${esc(c.l)}</div><h2>${esc(e.title)}</h2><dl class="detail-grid"><dt>Datum</dt><dd>${esc(fmt(e))}</dd><dt>Uhrzeit</dt><dd>${esc(e.timeText||'nicht angegeben')}</dd><dt>Ort</dt><dd>${esc([e.address,e.zip,e.place].filter(Boolean).join(', '))}</dd><dt>Quelle</dt><dd>${esc(e.sourceLabel||'Open Data')}</dd></dl><div class="actions">${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener">Quelle öffnen</a>`:'<span></span>'}${Number.isFinite(e.lat)?`<a href="${nav}" target="_blank" rel="noopener">Route</a>`:''}</div><section class="personal"><h3>Meine Erinnerung</h3><label class="check"><input id="dVisited" type="checkbox" ${p.visited?'checked':''}> Ich war hier</label><label class="check"><input id="dFavorite" type="checkbox" ${p.favorite?'checked':''}> Favorit / wieder hin</label><label>Bewertung 1–10<input id="dRating" type="range" min="0" max="10" value="${+p.rating||0}"><span id="ratingValue" class="ratingValue">${p.rating?p.rating+'/10':'–'}</span></label><label>Notiz<textarea id="dNote" placeholder="z. B. wenig Stände, Parken schlecht, Essen super …">${esc(p.note||'')}</textarea></label><label class="check"><input id="dAvoid" type="checkbox" ${p.avoid?'checked':''}> Nicht nochmal empfehlen</label><button id="savePref" class="save">Speichern</button></section>`;$('dRating').addEventListener('input',ev=>$('ratingValue').textContent=+ev.target.value?ev.target.value+'/10':'–');$('savePref').addEventListener('click',()=>{save(e,{visited:$('dVisited').checked,favorite:$('dFavorite').checked,rating:+$('dRating').value||0,note:$('dNote').value.trim(),avoid:$('dAvoid').checked,lastVisited:$('dVisited').checked?(p.lastVisited||iso(new Date())):''});doFilter();detail(e)});open('drawer','backdrop');const m=S.markers.get(e.id);if(m)S.map.panTo(m.getLatLng())}
  function history(){const h=$('historyList');h.innerHTML='';for(const p of allPrefs()){const d=document.createElement('div');d.className='event-card';d.style.gridTemplateColumns='1fr';d.innerHTML=`<div><div class="event-title">${esc(p.title||'Veranstaltung')}</div><div class="event-meta">${esc([p.address,p.zip,p.place].filter(Boolean).join(', '))}</div><div class="badges">${p.visited?'<span class="badge good">✓ besucht</span>':''}${p.rating?`<span class="badge">${p.rating}/10</span>`:''}${p.favorite?'<span class="badge good">★ Favorit</span>':''}${p.avoid?'<span class="badge bad">nicht nochmal</span>':''}</div>${p.note?`<p>${esc(p.note)}</p>`:''}</div>`;h.append(d)}if(!h.children.length)h.innerHTML='<div class="empty">Noch keine Besuche gespeichert.</div>';open('history','historyBackdrop')}
  function initMap(){S.map=L.map('map').setView([52.4,13.1],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap-Mitwirkende'}).addTo(S.map);S.layer=L.layerGroup().addTo(S.map)}
  function setup(){const cats=$('categories');Object.entries(C).forEach(([k,v])=>{const l=document.createElement('label');l.innerHTML=`<input type="checkbox" checked data-cat="${k}"> ${v.i} ${esc(v.l)}`;l.querySelector('input').addEventListener('change',ev=>{ev.target.checked?S.cats.add(k):S.cats.delete(k);doFilter()});cats.append(l)});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{S.preset=b.dataset.preset;$('date').value='';document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));doFilter()}));document.querySelectorAll('[data-region]').forEach(b=>b.addEventListener('click',()=>{S.region=b.dataset.region;document.querySelectorAll('[data-region]').forEach(x=>x.classList.toggle('active',x===b));doFilter()}));['search','date','time','openNow','hideBad','favorites','visited','radius','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',doFilter));$('locate').addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>{S.loc=[p.coords.latitude,p.coords.longitude];$('radius').disabled=false;$('locationState').textContent='Standort aktiv';doFilter()},()=>{$('locationState').textContent='Standort nicht freigegeben'}));$('filterBtn').addEventListener('click',()=>$('filters').classList.toggle('open'));$('historyBtn').addEventListener('click',history);$('closeDrawer').addEventListener('click',()=>close('drawer','backdrop'));$('backdrop').addEventListener('click',()=>close('drawer','backdrop'));$('closeHistory').addEventListener('click',()=>close('history','historyBackdrop'));$('historyBackdrop').addEventListener('click',()=>close('history','historyBackdrop'))}
  async function load(){try{const r=await fetch('/api/events');if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();S.events=(data.events||[]).map((e,i)=>{const x={...e,id:String(e.id||'e'+i)};x.category=cat(x);x.region=region(x);return x});$('status').textContent=`${S.events.length} Termine · täglich aktualisiert`;doFilter()}catch(e){console.error(e);$('status').textContent='Daten konnten nicht geladen werden';$('events').innerHTML='<div class="empty">Die Terminquelle ist gerade nicht erreichbar.</div>'}}
  initMap();setup();load();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
})();
