const SOURCES=[
 {key:'weekly',label:'Berlin Open Data – Berliner und Brandenburger Wochen- und Trödelmärkte',url:'https://www.berlin.de/sen/web/service/maerkte-feste/wochen-troedelmaerkte/index.php/index/all.geojson?q='},
 {key:'festivals',label:'Berlin Open Data – Berliner und Brandenburger Straßen- und Volksfeste',url:'https://www.berlin.de/sen/web/service/maerkte-feste/strassen-volksfeste/index.php/index/all.geojson?q='},
 {key:'christmas',label:'Berlin Open Data – Berliner und Brandenburger Weihnachtsmärkte',url:'https://www.berlin.de/sen/web/service/maerkte-feste/weihnachtsmaerkte/index.php/index/all.geojson?q='}
];
const DAY=86400;
const HEAD={'Content-Type':'application/json; charset=utf-8','Cache-Control':'public,max-age=3600,s-maxage=86400,stale-while-revalidate=3600','Access-Control-Allow-Origin':'*'};
function first(o,ks,f=''){for(const k of ks)if(o&&o[k]!=null&&String(o[k]).trim()!=='')return o[k];return f}
function point(feature,p){const g=feature?.geometry;if(g?.type==='Point'&&Array.isArray(g.coordinates)){const lon=+g.coordinates[0],lat=+g.coordinates[1];if(Number.isFinite(lat)&&Number.isFinite(lon))return{lat,lon}}const lat=+first(p,['lat','latitude','breitengrad','y'],NaN),lon=+first(p,['lon','lng','longitude','laengengrad','längengrad','x'],NaN);return{lat:Number.isFinite(lat)?lat:null,lon:Number.isFinite(lon)?lon:null}}
function normalize(feature,source,index){const p=feature?.properties||feature||{},pt=point(feature,p);return{id:`${source.key}-${first(p,['id','ID','nr','nummer'],index)}`,sourceType:source.key==='weekly'?'weekly':source.key,sourceLabel:source.label,title:String(first(p,['bezeichnung','name','titel','title','marktname'],'Unbenannte Veranstaltung')),address:String(first(p,['strasse','straße','adresse','address'],'')||''),zip:String(first(p,['plz','postleitzahl','zip'],'')||''),district:String(first(p,['bezirk','district','region','landkreis'],'')||''),place:String(first(p,['ort','stadt','gemeinde','place'],'')||''),from:String(first(p,['von','beginn','start','datum_von','start_date','date_from'],'')||''),to:String(first(p,['bis','ende','end','datum_bis','end_date','date_to'],'')||''),timeText:String(first(p,['zeit','zeiten','uhrzeit','oeffnungszeiten','öffnungszeiten','time'],'')||''),organizer:String(first(p,['veranstalter','anbieter','organizer'],'')||''),url:String(first(p,['www','website','url','link'],'')||''),notes:String(first(p,['bemerkungen','beschreibung','description','hinweis'],'')||''),lat:pt.lat,lon:pt.lon}}
async function fetchSource(source){const r=await fetch(source.url,{headers:{Accept:'application/geo+json,application/json;q=0.9'},cf:{cacheTtl:DAY,cacheEverything:true}});if(!r.ok)throw new Error(`${source.key}: HTTP ${r.status}`);const data=await r.json(),features=Array.isArray(data?.features)?data.features:Array.isArray(data?.index)?data.index:[];return features.map((f,i)=>normalize(f,source,i))}
function cleanHtml(html){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
async function fetchHavelblick(){const url='https://spd-ohv.de/';try{const r=await fetch(url,{headers:{Accept:'text/html'},cf:{cacheTtl:DAY,cacheEverything:true}});if(!r.ok)throw new Error('HTTP '+r.status);const html=await r.text();const pdf=[...html.matchAll(/href=["']([^"']*havelblick[^"']*\.pdf[^"']*|[^"']*1-2026[^"']*\.pdf[^"']*)["']/gi)][0]?.[1]||[...html.matchAll(/href=["']([^"']+\.pdf[^"']*)["']/gi)][0]?.[1]||'';const issue=pdf?new URL(pdf,url).href:'';const text=cleanHtml(html);const terms=/flohmarkt|trödelmarkt|troedelmarkt|erntefest|hoffest|dorffest|stadtfest|weihnachtsmarkt|handwerkermarkt|bauernmarkt|volksfest/ig;const mentions=[];let m;while((m=terms.exec(text))&&mentions.length<12){const a=Math.max(0,m.index-120),b=Math.min(text.length,m.index+260),snippet=text.slice(a,b).trim();if(!mentions.some(x=>x.snippet===snippet))mentions.push({snippet,url})}return{label:'Havelblick – SPD Oberhavel',homepage:url,latestIssueUrl:issue,mentions}}catch(e){return{label:'Havelblick – SPD Oberhavel',homepage:url,latestIssueUrl:'',mentions:[],error:String(e?.message||e)}}}
export async function onRequestGet(){const [settled,havelblick]=await Promise.all([Promise.allSettled(SOURCES.map(fetchSource)),fetchHavelblick()]);const events=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]),errors=settled.map((x,i)=>x.status==='rejected'?`${SOURCES[i].key}: ${x.reason?.message||'Fehler'}`:null).filter(Boolean);const payload={updatedAt:new Date().toISOString(),refreshIntervalHours:24,events,sources:SOURCES.map(s=>({key:s.key,label:s.label})),havelblick,partial:errors.length>0,errors};return new Response(JSON.stringify(payload),{status:events.length?200:502,headers:HEAD})}
